### ISSUE TITLE
Access to OSMLR segment geometries

### ISSUE THREAD

**Issue by drewda** [opentraffic/api#2]
The [OSMLR generator application](https://github.com/opentraffic/osmlr) generates geometries for each OSMLR segment as GeoJSON tiles. The Datastore will need to have access to these geometries in some form in order to respond to API queries for network statistics ( #1 ).

First, Datastore will need to be able to look up segments by bounding box. Second, Datastore will need to include geometries for the appropriate segments in API response.

//cc @kevinkreiser please edit or expand as you see fit!

**Comment by drewda** [comment]
OSMLR GeoJSON tiles are unprojected. On the other hand, this API will be powering a Leaflet "slippy map" interface. Should bounding box query parameters and geometry responses be projected into Web Mercator?

**Comment by kevinkreiser** [comment]
my opinion is that if we support mercator, we do it through standard tilespec queries, so someone would ask for tile x/y/z and we'd convert that to a bbox, get the features intersected as normal but reproject their geoms and clip them to the mercator bounds before returning them

**Comment by drewda** [comment]
Closed by https://github.com/opentraffic/api/pull/3 ?
